apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nifi.fullname" . }}
  labels:
    {{- include "nifi.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/affinity: cookie
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostName }}
        {{- range $i, $e := until (int .Values.global.nifi.nodeCount) }}
        - {{ printf "%s%d.%s" $.Values.ingress.nodeBaseHostName $i $.Values.ingress.hostName }}
        {{- end }}
      secretName: {{ include "nifi.fullname" . }}-tls
  rules:
    - host: {{ .Values.ingress.hostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nifi.fullname" . }}-http
                port:
                  name: https
          {{- range $name, $port := .Values.extraPorts }}
          {{- if $port.ingress }}
          - path: {{ $port.ingress.path | quote }}
            pathType: {{ $port.ingress.pathType | default "Exact" }}
            backend:
              service:
                name: {{ include "nifi.fullname" $ }}-http
                port:
                  name: {{ $name }}
          {{- end }}
          {{- end }}
    {{- range $i, $e := until (int .Values.global.nifi.nodeCount) }}
    - host: {{ printf "%s%d.%s" $.Values.ingress.nodeBaseHostName $i $.Values.ingress.hostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nifi.fullname" $ }}-node-{{ $i }}
                port:
                  name: https
    {{- end }}