apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi.fullname" . }}-http
  labels:
    {{- include "nifi.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.ports.https }}
      targetPort: https
      protocol: TCP
      name: https
    {{- if .Values.extraPorts }}
    {{- range $name, $port := .Values.extraPorts }}
    - name: {{ $name }}
      port: {{ $port.containerPort }}
      targetPort: {{ $port.containerPort }}
      protocol: {{ $port.protocol | default "TCP" }}
      {{- if $port.nodePort }}
      nodePort: {{ $port.nodePort }}
      {{- end }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "nifi.selectorLabels" . | nindent 4 }}
{{- range $i, $e := until (int .Values.global.nifi.nodeCount) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi.fullname" $ }}-node-{{ $i }}
  labels:
    {{- include "nifi.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ $.Values.ports.https }}
      targetPort: https
      protocol: TCP
      name: https
    {{- if $.Values.extraPorts }}
    {{- range $name, $port := $.Values.extraPorts }}
    - name: {{ $name }}
      port: {{ $port.containerPort }}
      targetPort: {{ $port.containerPort }}
      protocol: {{ $port.protocol | default "TCP" }}
      {{- if $port.nodePort }}
      nodePort: {{ $port.nodePort }}
      {{- end }}
    {{- end }}
    {{- end }}
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "nifi.fullname" $ }}-{{ $i }}
    {{- include "nifi.selectorLabels" $ | nindent 4 }}
{{- end }}