apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi.fullname" . }}-http
  labels:
    {{- include "nifi.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.https }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.ports.remoteinput }}
      targetPort: remoteinput
      protocol: TCP
      name: remoteinput
    {{- /* Only include extra ports that don't have a nodePort specified. For those that do, include them in a separate Service */}}
    {{- if not (include "nifi.hasNodePorts" . ) }}
    {{- range $name, $port := .Values.extraPorts }}
    {{- if not $port.nodePort }}
    - name: {{ $name }}
      port: {{ $port.containerPort }}
      targetPort: {{ $port.containerPort }}
      protocol: {{ $port.protocol | default "TCP" }}
      {{- if $port.nodePort }}
      nodePort: {{ $port.nodePort }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "nifi.selectorLabels" . | nindent 4 }}
{{- if eq (include "nifi.hasNodePorts" . ) "true" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi.fullname" . }}-nodeport
  labels:
    {{- include "nifi.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    {{- range $name, $port := .Values.extraPorts }}
    {{- if $port.nodePort }}
    - name: {{ $name }}
      port: {{ $port.containerPort }}
      targetPort: {{ $port.containerPort }}
      protocol: {{ $port.protocol | default "TCP" }}
      {{- if $port.nodePort }}
      nodePort: {{ $port.nodePort }}
      {{- end }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "nifi.selectorLabels" . | nindent 4 }}
{{- end }}
{{- range $i, $e := until (int .Values.global.nifi.nodeCount) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi.fullname" $ }}-node-{{ $i }}
  labels:
    {{- include "nifi.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ $.Values.ports.https }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "nifi.fullname" $ }}-{{ $i }}
    {{- include "nifi.selectorLabels" $ | nindent 4 }}
{{- end }}