apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi.fullname" . }}-http
  labels:
    {{- include "nifi.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.https }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.ports.datafeed }}
      targetPort: datafeed
      protocol: TCP
      name: datafeed
  selector:
    {{- include "nifi.selectorLabels" . | nindent 4 }}
{{- range $i, $e := until (int .Values.global.nifi.nodeCount) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi.fullname" $ }}-node-{{ $i }}
  labels:
    {{- include "nifi.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    {{- range $name, $number := $.Values.ports }}
    - name: {{ $name }}
      port: {{ $number }}
      protocol: TCP
    {{- end }}
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "nifi.fullname" $ }}-{{ $i }}
    {{- include "nifi.selectorLabels" $ | nindent 4 }}
{{- end }}