# Default values for nifi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  busybox:
    repository: busybox

  nifi:
    nodeCount: 1

  encryption:
    sensitivePropertiesKey:
      secretRef:
        name: ""
        key: ""

  tls:
    certificate:
      duration: 8760h # 365 days
      renewBefore: 168h # 7 days
      keystorePasswordSecretRef:
        name: ""
        key: password
      issuerRef:
        name: ""
        kind: ClusterIssuer

  ldap:
    url: "" # ldaps://dc-1.example.com:636,ldaps://dc-2.example.com:636
    tlsProtocol: TLSv1.2
    authenticationStrategy: LDAPS # ANONYMOUS|SIMPLE|LDAPS|START_TLS
    identityStrategy: USE_USERNAME # USE_DN|USE_USERNAME
    initialAdminIdentity: "" # CN=Administrator,DC=example,DC=com
    manager:
      distinguishedName: "" # CN=Administrator,DC=example,DC=com
      passwordSecretRef:
        name: ""
        key: ""
    userSearchBase: "" # DC=example,DC=com
    userSearchFilter: sAMAccountName={0}

image:
  repository: apache/nifi
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# Set to `true` to pause at startup before loading the application
debugStartup: false

ui:
  refreshInterval: 10 sec
  timeZone: "" # IANA timezone identifier. Time is displayed using this timezone in the UI.
  maxThreads: "" # Maximum number of Jetty threads to use for UI and HTTP site-to-site connections

encryption:
  # Used to encrypt all repositories
  repository:
    keyId: 1
    secretRef:
      name: ""
      key: repository.p12 # File extension must be either .p12 or .bcfks

# Override log verbosity settings in conf/logback.xml
logging:
  levels: { }
#    org.apache.nifi.web.security: DEBUG

persistence:
  config:
    path: conf
    files:
      authorizations: authorizations.xml
      users: users.xml
      flowJson: flow.json.gz
    dirs:
      archive: archive
  repo:
    path: repo
    dirs:
      flowfile: flowfile
      content: content
      provenance: provenance

ports:
  https: 8443
  cluster: 11443
  remoteinput: 10443
  loadbalance: 6342

cluster:
  enabled: true
  traffic:
    maxThreads: 100 # Max number of threads used for inter-node communication
  zookeeper:
    connectionString: "" # zk01:2181,zk02:2181,zk03:2181
    rootNode: /nifi

metrics:
  # Expose metrics for each node via Ingress
  ingress:
    enabled: false
    basePath: /metrics # Metrics are available externally via Ingress for each pod at: /metrics/<pod name>
    requireClientCertificate: false

  # Create a ServiceMonitor to enable Prometheus to scrape metrics from each pod
  serviceMonitor:
    enabled: false
    interval: 10s

# Additional ports and Ingress rules to configure for each node
extraPorts:
  datafeed:
    containerPort: 9443
    protocol: TCP
    nodePort: "" # Set if NodePort is required
    ingress:
      path: /datafeed # Omit if ingress is not required
      pathType: Exact

# Extra config properties to set at runtime
extraConfig:
  nifiProperties: { }
  # nifi.cluster.node.connection.timeout: 5 secs

extraEnv: [ ]
#  - name: MY_VAR
#    value: "some value"

extraVolumes: [ ]
#  - name: my-volume
#    nfs:
#      server: fs.example.com
#      path: /my-volume

extraVolumeMounts: [ ]
#  - mountPath: /data/vol-1
#    name: my-volume

ingress:
  enabled: true
  ingressClassName: nginx
  hostName: example.com # nifi.example.com
  siteToSite:
    subDomain: s2s # Subdomain for site-to-site traffic (e.g. s2s.example.com)
  annotations: { }

jvmHeap:
  min: 512m
  max: 1g

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 2Gi

volumeClaims:
  data: { }
#    storageClassName: ""
#    selector:
#      matchLabels: { }
#      matchExpressions: { }
#    accessModes:
#      - ReadWriteOnce
#    resources:
#      requests:
#        storage: ""
#      limits:
#        storage: ""

nodeSelector: { }
tolerations: [ ]
affinity: { }
