# Default values for nifi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  containerRegistry: ""

  nifi:
    nodeCount: 1

  encryption:
    sensitivePropertiesKey:
      secretRef:
        name: ""
        key: ""

  tls:
    certificate:
      duration: 8760h # 365 days
      renewBefore: 168h # 7 days
      keystorePasswordSecretRef:
        name: ""
        key: password
      issuerRef:
        name: ""
        kind: ClusterIssuer

  ldap:
    url: "" # ldaps://dc-1.example.com:636,ldaps://dc-2.example.com:636
    tlsProtocol: TLSv1.2
    authenticationStrategy: LDAPS # ANONYMOUS|SIMPLE|LDAPS|START_TLS
    identityStrategy: USE_USERNAME # USE_DN|USE_USERNAME
    initialAdminIdentity: "" # CN=Administrator,DC=example,DC=com
    manager:
      distinguishedName: "" # CN=Administrator,DC=example,DC=com
      passwordSecretRef:
        name: ""
        key: ""
    userSearchBase: "" # DC=example,DC=com
    userSearchFilter: sAMAccountName={0}

image:
  repository: apache/nifi
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# Set to `true` to pause at startup before loading the application
debugStartup: false

uiRefreshInterval: 10 sec

encryption:
  # Used to encrypt all repositories
  repository:
    keyId: 1
    secretRef:
      name: ""
      key: "" # 64-character hex-encoded key

persistence:
  config:
    path: conf
    files:
      authorizations: authorizations.xml
      users: users.xml
      flowJson: flow.json.gz
    dirs:
      archive: archive
  repo:
    path: repo
    dirs:
      flowfile: flowfile
      content: content
      provenance: provenance

ports:
  https: 8443
  cluster: 11443
  remoteinput: 10000
  loadbalance: 6342
  datafeed: 9443

cluster:
  enabled: true
  traffic:
    maxThreads: 50 # Max number of threads used for inter-node communication
  zookeeper:
    connectionString: "" # zk01:2181,zk02:2181,zk03:2181
    rootNode: /nifi

# Extra config properties to set at runtime
extraConfig:
  nifiProperties: { }
  # nifi.cluster.node.connection.timeout: 5 secs

extraEnv: [ ]
#  - name: MY_VAR
#    value: "some value"

ingress:
  enabled: true
  ingressClassName: nginx
  hostName: "" # nifi.example.com
  nodeBaseHostName: "node-" # Subdomain prefix for external traffic
  annotations: { }

jvmHeap:
  min: 512m
  max: 1g

resources:
  requests:
    cpu: 100m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi

volumeClaims:
  data: { }
#    storageClassName: ""
#    selector:
#      matchLabels: { }
#      matchExpressions: { }
#    accessModes:
#      - ReadWriteOnce
#    resources:
#      requests:
#        storage: ""
#      limits:
#        storage: ""

nodeSelector: { }
tolerations: [ ]
affinity: { }
