apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi-registry.fullname" . }}
  labels:
    {{- include "nifi-registry.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nifi-registry.selectorLabels" . | nindent 4 }}
