apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nifi-registry.fullname" . }}
  labels:
    {{- include "nifi-registry.labels" . | nindent 4 }}
data:
  providers.xml: |
    {{- /* Mounted where an external database is used */}}
    <flowPersistenceProvider>
        <class>org.apache.nifi.registry.provider.flow.DatabaseFlowPersistenceProvider</class>
    </flowPersistenceProvider>

  custom-startup.sh: |
    #!/bin/bash -e

    scripts_dir='/opt/nifi-registry/scripts'
    [ -f "${scripts_dir}/common.sh" ] && . "${scripts_dir}/common.sh"

    authorizers_file='conf/authorizers.xml'
    login_providers_file='conf/identity-providers.xml'

    {{- /* Grant nodes cluster permissions */}}
    list_identities () {
      node_identities=""
      for (( i = 0; i < {{ .Values.global.nifi.nodeCount }}; i++ )); do
        node_dn="CN={{ include "nifi.fullname" . }}-${i}.{{ include "nifi.fullname" . }}"
        node_identities="${node_identities}<property name=\"$1 Node-${i}\">${node_dn}</property>\n"
      done
      sed -i -E "s|(<\!--)?(<property name=\"$1 1\">.*</property>)(-->)?|\2\n${node_identities}|g" "${authorizers_file}"
    }
    list_identities 'NiFi Identity'
    list_identities 'Initial User Identity'

    {{- /* Set LDAP TLS properties (as Docker image `update_login_providers.sh` mistakenly updates, instead of inserts elements */}}
    insert_property () {
      property_name=$1
      property_value=$2
      if [ -n "${property_value}" ]; then
        xmlstarlet ed --inplace --subnode '//identityProviders/provider[1]' --type elem --name 'property' --value "${property_value}" \
          --var node '$prev' \
          --insert '$node' --type attr --name 'name' --value "${property_name}" \
          "${login_providers_file}"
      fi
    }
    # Remove comments to enable the ldap-provider
    sed -i '/To enable the ldap-identity-provider remove/d' "${login_providers_file}"
    insert_property 'TLS - Keystore'              "${LDAP_TLS_KEYSTORE}"
    insert_property 'TLS - Keystore Password'     "${LDAP_TLS_KEYSTORE_PASSWORD}"
    insert_property 'TLS - Keystore Type'         "${LDAP_TLS_KEYSTORE_TYPE}"
    insert_property 'TLS - Truststore'            "${LDAP_TLS_TRUSTSTORE}"
    insert_property 'TLS - Truststore Password'   "${LDAP_TLS_TRUSTSTORE_PASSWORD}"
    insert_property 'TLS - Truststore Type'       "${LDAP_TLS_TRUSTSTORE_TYPE}"
    insert_property 'TLS - Protocol'              "${LDAP_TLS_PROTOCOL}"

    {{- /* Set config file paths to persistent locations */}}
    conf_dir='./data/conf'
    {{- with .Values.persistence }}
    sed -i -E "s|(<property name=\"Users File\">).*(</property>)|\1${conf_dir}/{{ .config.files.users }}\2|g" "${authorizers_file}"
    {{- end }}

    {{- /* Generate a TLS cert for this node from the CSI-provided certificates and private key */}}
    cert_dir='/opt/certmanager'
    tls_dir='/opt/tls'
    rm -f $tls_dir/*
    openssl pkcs12 -export \
      -in $cert_dir/tls.crt \
      -inkey $cert_dir/tls.key \
      -CAfile $cert_dir/ca.crt \
      -passout "pass:${KEYSTORE_PASSWORD}" \
      -out $tls_dir/keystore.p12
    keytool -import -noprompt -trustcacerts \
      -file $cert_dir/ca.crt \
      -storepass "${TRUSTSTORE_PASSWORD}" \
      -destkeystore $tls_dir/truststore.p12 \
      -deststoretype pkcs12

    {{- range $key, $value := .Values.extraConfig.nifiRegistryProperties }}
    prop_replace {{ $key | squote }} {{ $value | quote }}
    {{- end }}

    exec $scripts_dir/start.sh
