#
# apache/nifi-registry wants to run as user 1000,
# bind the service account to scc:non-root to allow this to work.
#
{{- if .Values.global.openshift.version }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nifi-sa-scc-nonroot
subjects:
  - kind: ServiceAccount
    name: nifi
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:nonroot'
{{- end }}
